// <auto-generated />
namespace TISelvagem.RepositorioEF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class BancoInicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BancoInicial));
        
        string IMigrationMetadata.Id
        {
            get { return "201308011621114_BancoInicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
